-- vim.keymap.set("n", "<C-p>", ":Telescope")
vim.keymap.set("n", "<leader>ts", ":lua require('telescope.builtin').grep_string({ search = vim.fn.input(\"Grep For > \")})<CR>")
vim.keymap.set("n", "<C-p>", ":lua require('telescope.builtin').git_files()<CR>")
vim.keymap.set("n", "<Leader>tf", ":lua require('telescope.builtin').find_files()<CR>")

vim.keymap.set("n", "<leader>tw", ":lua require('telescope.builtin').grep_string { search = vim.fn.expand(\"<cword>\") }<CR>")
vim.keymap.set("n", "<leader>tb", ":lua require('telescope.builtin').buffers()<CR>")
vim.keymap.set("n", "<leader>vh", ":lua require('telescope.builtin').help_tags()<CR>")
vim.keymap.set("n", "<leader>trc", ":lua require('theprimeagen.telescope').search_dotfiles({ hidden = true })<CR>")
vim.keymap.set("n", "<leader>va", ":lua require('theprimeagen.telescope').anime_selector()<CR>")
vim.keymap.set("n", "<leader>tc", ":lua require('theprimeagen.telescope').chat_selector()<CR>")
vim.keymap.set("n", "<leader>tc", ":lua require('theprimeagen.telescope').git_branches()<CR>")
vim.keymap.set("n", "<leader>gw", ":lua require('telescope').extensions.git_worktree.git_worktrees()<CR>")
vim.keymap.set("n", "<leader>gm", ":lua require('telescope').extensions.git_worktree.create_git_worktree()<CR>")
vim.keymap.set("n", "<leader>td", ":lua require('theprimeagen.telescope').dev()<CR>")
