#!/usr/bin/env bash

# remove the old nvim config
rm -rdf ${HOME}/.config/nvim

if [[ -z "$1" || "$1" == "lua" ]];  then
  # add the new one
  stow -vSt ${HOME} nvim-lua-config-theprimeagen
elif [[ "$1" == "chris" ]]; then
  # add the new one
  stow -vSt ${HOME} nvim-config-chris
elif [[ "$1" == "lazy" ]]; then
  # add the new one
  stow -vSt ${HOME} nvim_lazy_vim
else
  # add the new one
  stow -vt ${HOME} nvim
fi
