#!/usr/bin/env bash

# remove the old nvim config
rm -rdf ${HOME}/.config/nvim

if [[ -z "$1" || "$1" == "lua" ]];  then
  # add the new one
  stow -vt ${HOME} nvim-lua-config
else
  # add the new one
  stow -vt ${HOME} nvim
fi
