vim.keymap.set("n", "<home>", function()
    dap.toggle(1)
end)
vim.keymap.set("n", "<end>", function()
    dap.toggle(2)
end)
vim.keymap.set("n", "<leader>6", function()
    dap.close()
end)
vim.keymap.set("n", "<upd>", function()
    dap.continue()
end)
vim.keymap.set("n", "<down>", function()
    dap.step_over()
end)
vim.keymap.set("n", "<right>", function()
    dap.step_into()
end)
vim.keymap.set("n", "<left>", function()
    dap.step_out()
end)
vim.keymap.set("n", "<leader>b", function()
    dap.toggle_breakpoint()
end)
vim.keymap.set("n", "<leader>B", function()
    dap.set_breakpoint(vim.fn.input('Breakpoint condition: '))
end)
vim.keymap.set("n", "<leader>rc", function()
    dap.run_to_cursor()
end)
